In [1]:
import numpy as np

In [2]:
a1 = np.array([1, 2, 3])

In [4]:
a1

array([1, 2, 3])

In [6]:
a2 = np.array([[1, 2, 3],
                 [4, 5, 6]])
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
a3 = np.array([[[1, 2, 3],
                [4, 5, 6]],
               [[7, 8, 9],
                [10, 11, 12]],
               [[13, 14, 15],
                [16, 17, 18]]])
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])

In [14]:
a1.shape, a1.ndim, a1.dtype, a1.size, type(a1)

((3,), 1, dtype('int32'), 3, numpy.ndarray)

In [15]:
a2.shape, a2.ndim, a2.dtype, a2.size, type(a2)

((2, 3), 2, dtype('int32'), 6, numpy.ndarray)

In [16]:
a3.shape, a3.ndim, a3.dtype, a3.size, type(a3)

((3, 2, 3), 3, dtype('int32'), 18, numpy.ndarray)

In [17]:
import pandas as pd

In [18]:
df = pd.DataFrame(a2)

In [19]:
df

0  1  2
0  1  2  3
1  4  5  6

In [20]:
ones = np.ones((10, 2))

In [21]:
ones

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [23]:
zeros = np.zeros((7, 2, 3))
zeros

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [24]:
range_array = np.arange(0, 100, 3)
range_array

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [25]:
random_array = np.random.randint(10, size=(7, 2))
random_array

array([[1, 7],
       [6, 4],
       [9, 7],
       [7, 9],
       [8, 7],
       [8, 9],
       [2, 7]])

In [26]:

np.random.random((3, 5))

array([[0.61746399, 0.07897171, 0.39850271, 0.72966976, 0.16448824],
       [0.32685805, 0.63088654, 0.62312451, 0.25725602, 0.92563422],
       [0.62913778, 0.77555612, 0.23148555, 0.25104157, 0.65685789]])

In [28]:
np.random.seed(42)
np.random.randint(10, size=(4, 6))

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

In [30]:
randm = np.random.randint(1, 10, size=(3, 7))
randm

array([[7, 8, 3, 1, 4, 2, 8],
       [4, 2, 6, 6, 4, 6, 2],
       [2, 4, 8, 7, 9, 8, 5]])

In [32]:
np.unique(randm)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
randm[0]

array([7, 8, 3, 1, 4, 2, 8])

In [34]:
randm[:2]

array([[7, 8, 3, 1, 4, 2, 8],
       [4, 2, 6, 6, 4, 6, 2]])

In [35]:
randm[:2, :2]

array([[7, 8],
       [4, 2]])

In [36]:
a4 = np.random.randint(10, size=(3, 5))
ones = np.ones((3, 5))

In [37]:
a4 + ones

array([[ 2.,  5.,  8., 10.,  9.],
       [ 9.,  1.,  9.,  7.,  9.],
       [ 8.,  1.,  8.,  8.,  3.]])

In [38]:
ones = np.ones((5, 3))

In [39]:
a4 + ones

ValueError: operands could not be broadcast together with shapes (3,5) (5,3) 

In [40]:
ones = np.ones((3, 5))

In [41]:
a4 - ones

array([[ 0.,  3.,  6.,  8.,  7.],
       [ 7., -1.,  7.,  5.,  7.],
       [ 6., -1.,  6.,  6.,  1.]])

In [42]:
a4 * ones

array([[1., 4., 7., 9., 8.],
       [8., 0., 8., 6., 8.],
       [7., 0., 7., 7., 2.]])

In [43]:
a4 ** 2

array([[ 1, 16, 49, 81, 64],
       [64,  0, 64, 36, 64],
       [49,  0, 49, 49,  4]], dtype=int32)

In [44]:
np.square(a4)

array([[ 1, 16, 49, 81, 64],
       [64,  0, 64, 36, 64],
       [49,  0, 49, 49,  4]], dtype=int32)

In [45]:
np.mean(a4)

5.466666666666667

In [46]:
np.max(a4)

9

In [48]:
np.min(a4)

0

In [49]:
np.std(a4)

3.0739045022396008

In [50]:
np.var(a4)

9.448888888888888

In [51]:
a4.shape

(3, 5)

In [52]:
a4.reshape(3, 5, 1)

array([[[1],
        [4],
        [7],
        [9],
        [8]],

       [[8],
        [0],
        [8],
        [6],
        [8]],

       [[7],
        [0],
        [7],
        [7],
        [2]]])

In [53]:
a4.T

array([[1, 8, 7],
       [4, 0, 0],
       [7, 8, 7],
       [9, 6, 7],
       [8, 8, 2]])

In [54]:
mat1 = np.random.randint(10, size=(3, 3))
mat2 = np.random.randint(10, size=(3, 2))

In [56]:
mat1

array([[0, 7, 2],
       [2, 0, 4],
       [9, 6, 9]])

In [57]:
mat2

array([[8, 6],
       [8, 7],
       [1, 0]])

In [55]:
np.dot(mat1, mat2)

array([[ 58,  49],
       [ 20,  12],
       [129,  96]])

In [58]:
mat3 = np.random.randint(10, size=(4, 3))
mat4 = np.random.randint(10, size=(4, 3))

In [59]:
np.dot(mat3, mat4)

ValueError: shapes (4,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

In [60]:
np.dot(mat3.T, mat4)

array([[ 81,  93, 102],
       [ 54,  54,  86],
       [ 54,  70, 125]])

In [61]:
mat5 = np.random.randint(10, size=(4, 2))
mat6 = np.random.randint(10, size=(4, 2))

In [62]:
mat5 > mat6

array([[ True, False],
       [False,  True],
       [False,  True],
       [False, False]])

In [63]:
mat5 >= mat6

array([[ True, False],
       [False,  True],
       [False,  True],
       [False, False]])

In [64]:
mat5 > 7

array([[False, False],
       [False, False],
       [False, False],
       [False, False]])

In [66]:
mat5 == mat6

array([[False, False],
       [False, False],
       [False, False],
       [False, False]])

In [67]:
np.sort(mat5)

array([[3, 4],
       [6, 6],
       [3, 6],
       [2, 5]])

In [68]:
np.argsort(mat6)

array([[0, 1],
       [1, 0],
       [1, 0],
       [1, 0]], dtype=int64)

In [69]:
np.argmax(mat5)

2

In [70]:
np.argmin(mat6)

0

In [71]:
np.argmax(mat5, axis=1)

array([1, 0, 1, 1], dtype=int64)

In [72]:
np.argmin(mat6, axis=0)

array([0, 2], dtype=int64)

In [73]:
np.random.randn(3, 5)

array([[-0.30928855,  0.6731255 , -0.25663018, -0.36782572,  1.27373362],
       [-0.29195267, -2.65517605,  0.34551794, -0.39551645, -0.28913686],
       [ 0.45293633, -0.16606091,  0.21493883, -2.02231493, -0.94305681]])

In [74]:
np.linspace(1, 100, 10)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])